name: Test
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
    inputs:
      base_ipa_url:
        description: "test"
        required: false
jobs:
  t:
    runs-on: macos-14
    steps:
      - run: echo hello
